# -*- coding: utf-8 -*-
"""Amazon_review_sentiment_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qq92v7Xg96bOwtdo0bvjVEUgkExbuctB
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

df = pd.read_csv('/content/sample_data/Reviews.csv', on_bad_lines='skip', encoding='latin-1', engine='python')

df.head()

df.shape

df.columns

df = df[['Text', 'Score']]
df.head()

def convert_sentiment(score):
    if score <= 2:
        return "negative"
    elif score == 3:
        return "neutral"
    else:
        return "positive"

df['sentiment'] = df['Score'].apply(convert_sentiment)
df.head()

df = df.dropna(subset=['Text'])
df.shape

X = df['Text']
y = df['sentiment']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

tfidf = TfidfVectorizer(
    stop_words='english',
    max_features=50000
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

model = LogisticRegression(max_iter=2000)
model.fit(X_train_tfidf, y_train)

y_pred = model.predict(X_test_tfidf)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

sample = ["The product quality is amazing, I love it!"]
sample_vec = tfidf.transform(sample)
model.predict(sample_vec)

